### ISSUE TITLE
Specific id periodically goes south

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [web-scheduler/web-scheduler#244]
### Describe the bug

I have two ids that I've been using with the web scheduler.   The id jauerbach is lightly used.   The id serverless-eng is more heavily used, mostly via the API rather than the UI.

Twice (including currently) the more heavily used id stops working.   This has never happened, at least with similar symptoms, to the other id.  The first time, I reported this informally and something (i don't know what) was done to fix it.  This time, I decided to open a ticket as a way to record the problem a little more thoroughly.

From the API, the symptom (in response to a GET on the path `/scheduledTasks`, that is a list request) is 
```
{
   type: 'https://tools.ietf.org/html/rfc7231#section-6.5.4',
   title: 'Not Found',
   status: 404,
   traceId: '00-3e23be955aeb1417547cb86b168a5124-00ff94b13ca95888-00'
```

From the UI, a login to the id succeeds.   But, when I attempt to bring up the scheduled tasks list page, the page hangs in the busy indicator, and periodically there is a pop-up: "Error loading task list.  There was an error loading this page.  Please try again."   The pop-up goes away after a few seconds, only to reappear some 10-15 seconds later.   In the browser dev console, observing the API traffic generated by the API, 

```
Request URL: https://scheduler.nullreference.io/api/ScheduledTasks?api-version=1.0&Offset=0&PageSize=10
Request Method: GET
Status Code: 404 
Remote Address: [2606:4700::6810:f34e]:443
Referrer Policy: strict-origin-when-cross-origin
:authority: scheduler.nullreference.io
:method: GET
:path: /api/ScheduledTasks?api-version=1.0&Offset=0&PageSize=10
:scheme: https
accept: *
```

Now that I record this information I am not really certain that the symptom was the same the last time around.   Same id, yes, same surface symptom (inability to load the task list) but my recollection was that the errors were 500s rather than 404s.   My recollection may be imperfect.   I'm hoping that the current symptom (and the enduring broken state of the id) will be enough to debug and fix whatever is indicated by the present symptom.

### Steps to reproduce

It may be impossible to reproduce this on any other id.   If necessary I can supply the login information for the troubled id.  But, I'm hoping the fact that I can reproduce it is enough, since I would hope some internal traces of the problem will be generated.

### Expected behaviour

All ids should continue to work and be able to list tasks.

_Moderation note: Removed PII._

**Comment by ElanHasson** [comment]
This seems to have been resolved by #243
